import { Alike } from 'next/font/google';
import './globals.css';
import { Suspense } from 'react';

const alike = Alike({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alike.className}>{children}</body>
    </html>
  );
}
